# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-a8bh3dx-states"
    dynamodb_table = "terragrunt-lock-table"
    encrypt        = true
    key            = "prod/module-2.tfstate"
    region         = "ap-southeast-2"
  }
}
