# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    region         = "ap-southeast-2"
    bucket         = "terragrunt-a8bh3dx-states"
    dynamodb_table = "terragrunt-lock-table"
    encrypt        = true
    key            = "module-2/terraform.tfstate"
  }
}
